<a href="https://colab.research.google.com/github/ELLLELEE/Deeplearning/blob/main/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensor0d = torch.tensor(3)

In [3]:
tensor0d.dtype

torch.int64

In [7]:
tensor2d = torch.tensor([[1, 2], [5, 3]])


In [8]:
tensor1d = torch.tensor([1,2,3])

In [9]:
print(tensor1d.dtype)

torch.int64


In [10]:
tensor1d = torch.tensor([1,2])

In [11]:
tensor2d = torch.tensor([[5/8, 3/8], [5/8, 3/8]])

In [12]:
tensor2d @ tensor2d.T

tensor([[0.5312, 0.5312],
        [0.5312, 0.5312]])

In [13]:
import torch
import torch.nn.functional as F


In [26]:
y = torch.tensor([1.0])  # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0])

In [30]:
z = x1 * w1 + b

In [31]:
a = torch.sigmoid(z)

In [32]:
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


In [34]:
import torch.nn.functional as F
from torch.autograd import grad

In [40]:
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2],requires_grad =True)

b = torch.tensor([0.0],requires_grad =True)

z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a,y)

grad_L_w1 = grad(loss, w1, retain_graph = True)
grad_L_b = grad(loss, b, retain_graph=True)

In [42]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [43]:
loss.backward()

In [45]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [48]:
class NeuralNetwork(torch.nn.Module):
  def __init__(self, num_inputs, num_outputs):
    super().__init__()

    self.layer = torch.nn.Sequential(
        torch.nn.Linear(num_inputs, 30),
        torch.nn.ReLU(),

        torch.nn.Linear(30, 20),
        torch.nn.ReLU(),

        torch.nn.Linear(20, num_outputs),
    )
  def forward(self,x):
    logit = self.layers(x)
    return logit

In [58]:
model = NeuralNetwork(50,3)


In [59]:
print(model)

NeuralNetwork(
  (layer): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [60]:
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print(num_params)

2213


In [62]:
print(model.layer[0].weight)

Parameter containing:
tensor([[ 0.0042, -0.1237, -0.1092,  ..., -0.0326,  0.0015,  0.0478],
        [ 0.0394, -0.0893, -0.0277,  ...,  0.1245, -0.1198,  0.0393],
        [ 0.1403,  0.0232,  0.0062,  ..., -0.1019, -0.1048,  0.0606],
        ...,
        [-0.0769, -0.0533, -0.0846,  ..., -0.0296,  0.1248, -0.1113],
        [ 0.0567, -0.0560,  0.0102,  ..., -0.0492, -0.1046,  0.0136],
        [ 0.0623,  0.0156, -0.0446,  ...,  0.1334,  0.0346,  0.0457]],
       requires_grad=True)


In [63]:
print(model.layer[0].weight.shape)

torch.Size([30, 50])


In [66]:
torch.manual_seed(123)

mpdel = NeuralNetwork(50,3)
print(model.layer[0].weight)

Parameter containing:
tensor([[ 0.0042, -0.1237, -0.1092,  ..., -0.0326,  0.0015,  0.0478],
        [ 0.0394, -0.0893, -0.0277,  ...,  0.1245, -0.1198,  0.0393],
        [ 0.1403,  0.0232,  0.0062,  ..., -0.1019, -0.1048,  0.0606],
        ...,
        [-0.0769, -0.0533, -0.0846,  ..., -0.0296,  0.1248, -0.1113],
        [ 0.0567, -0.0560,  0.0102,  ..., -0.0492, -0.1046,  0.0136],
        [ 0.0623,  0.0156, -0.0446,  ...,  0.1334,  0.0346,  0.0457]],
       requires_grad=True)


In [73]:
torch.manual_seed(123)
X = torch.rand((1,50))
out = model.forward(X)
print(out)

AttributeError: 'NeuralNetwork' object has no attribute 'layers'

In [77]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9,2.9],
    [-0.5,2.6],
    [2.3,-1.1],
    [2.7,-1.5]
])
y_train = torch.tensor([0,0,0,1,1])

In [78]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [79]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [83]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset= train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=()

)

TypeError: '<' not supported between instances of 'tuple' and 'int'

In [84]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset= train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=()

)

TypeError: '<' not supported between instances of 'tuple' and 'int'

In [ ]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)

        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

In [ ]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)

# New: Define a device variable that defaults to a GPU.
device = torch.device("cuda")
# New: Transfer the model onto the GPU.
model.to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        # New: Transfer the data onto the GPU.
        features, labels = features.to(device), labels.to(device)
        logits = model(features)
        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation